module(..., package.seeall)

local DAILYTASKID_CURRENT_TASKTable = {}
local DAILYTASKID_FIVESTAR_AWARDTable = {}
local DAILYTASKID_REFRESH_TASKTable = {}
local DAILYTASKID_COMPLETE_TASKTable = {}
local DAILYTASKID_GET_AWARDTable = {}
local DAILYTASKID_TASK_STATUS_CHANGETable = {}

--[[--
]]
function getDAILYTASKID_CURRENT_TASKTable()
	return DAILYTASKID_CURRENT_TASKTable
end

function readDAILYTASKID_CURRENT_TASK(dataTable)
	DAILYTASKID_CURRENT_TASKTable = dataTable
	framework.emit(DAILYTASKID_CURRENT_TASK)
end

function getDAILYTASKID_FIVESTAR_AWARDTable()
	return DAILYTASKID_FIVESTAR_AWARDTable
end

function readDAILYTASKID_FIVESTAR_AWARD(dataTable)
	DAILYTASKID_FIVESTAR_AWARDTable = dataTable
	framework.emit(DAILYTASKID_FIVESTAR_AWARD)
end

function getDAILYTASKID_REFRESH_TASKTable()
	return DAILYTASKID_REFRESH_TASKTable
end

function readDAILYTASKID_REFRESH_TASK(dataTable)
	DAILYTASKID_REFRESH_TASKTable = dataTable
	framework.emit(DAILYTASKID_REFRESH_TASK)
end

function getDAILYTASKID_COMPLETE_TASKTable()
	return DAILYTASKID_COMPLETE_TASKTable
end

function readDAILYTASKID_COMPLETE_TASK(dataTable)
	DAILYTASKID_COMPLETE_TASKTable = dataTable
	framework.emit(DAILYTASKID_COMPLETE_TASK)
end

--[[--
]]
function getDAILYTASKID_GET_AWARDTable()
	return DAILYTASKID_GET_AWARDTable
end

function readDAILYTASKID_GET_AWARD(dataTable)
	DAILYTASKID_GET_AWARDTable = dataTable
	framework.emit(DAILYTASKID_GET_AWARD)
end

function readDAILYTASKID_TASK_STATUS_CHANGE(dataTable)
	DAILYTASKID_TASK_STATUS_CHANGETable = dataTable
	framework.emit(DAILYTASKID_TASK_STATUS_CHANGE)
end

function getDAILYTASKID_TASK_STATUS_CHANGE()
	return DAILYTASKID_TASK_STATUS_CHANGETable
end

function getDAILYTASKID_TASK_STATUS_CHANGE_RESULT()
	local result = nil
	if DAILYTASKID_TASK_STATUS_CHANGETable["Result"] ~= nil then
		result = DAILYTASKID_TASK_STATUS_CHANGETable["Result"]
	end
	return result
end

registerMessage(DAILYTASKID_CURRENT_TASK, readDAILYTASKID_CURRENT_TASK)
registerMessage(DAILYTASKID_FIVESTAR_AWARD, readDAILYTASKID_FIVESTAR_AWARD)
registerMessage(DAILYTASKID_REFRESH_TASK, readDAILYTASKID_REFRESH_TASK)
registerMessage(DAILYTASKID_COMPLETE_TASK, readDAILYTASKID_COMPLETE_TASK)
registerMessage(DAILYTASKID_GET_AWARD, readDAILYTASKID_GET_AWARD)
registerMessage(DAILYTASKID_TASK_STATUS_CHANGE, readDAILYTASKID_TASK_STATUS_CHANGE)